### ISSUE TITLE
Feature request: Add link preview

### ISSUE THREAD

**Issue by wnhrt** [Livinglist/Hacki#100]
Add option to enable link preview, like on Hacker News.

e.g. a thread about `github.com/Livinglist/Hacki` would show `github.com/Livinglist`
or `www.example.com/path/to/article` would show `example.com`

In list view the link could appear in its own line, like the metadata.
And in discussion view it could appear below the title.

**Comment by Livinglist** [comment]
Long time no see and thanks for suggesting new features! This should be pretty straightforward.
