### ISSUE TITLE
Feature - swipe between pages

### ISSUE THREAD

**Issue by octoshrimpy** [Livinglist/Hacki#113]
Between top, best, new, etc. This would ruin swipe actions, but those could be triggered by long press.

**Comment by Livinglist** [comment]
Thanks for suggesting new features! 

I agree that being unable to swipe between tabs can be annoying sometimes. need to figure out how to make swipe actions and this co-exist (if possible that is)

**Comment by octoshrimpy** [comment]
should be possible. if user toggles on "swipe between pages" in settings, then warn with a toast that swipe actions have been replaced by a longpress menu. I'm thinking maybe one of those android 11 new menus that enters screen from the bottom, style-wise.
