### ISSUE TITLE
Feature - slide to article from comments

### ISSUE THREAD

**Issue by octoshrimpy** [Livinglist/Hacki#133]
going inline with #132, Materialistic has a really nice feature where you can swipe left/right between comments and the article. If slide nav was turned on, it would be cool to slide to article and back to comments

**Comment by Livinglist** [comment]
Hi @octoshrimpy, since I don't have an Android phone, can you share with me a video clip showcasing the action in Materialistic?

**Comment by octoshrimpy** [comment]
Heres the recording

**Comment by octoshrimpy** [comment]
I went ahead and gave you a visual tour through the app :)
