### ISSUE TITLE
Option to disable all popup or banners

### ISSUE THREAD

**Issue by Moxville** [Livinglist/Hacki#16]
Every time when I click a story I see this popup or banner (in orange color) with a caption 
example: 
Fav a Story 
add it to your favorites

I noticed similar banners as well in the app. Orange banner / popup never goes off.

I could not find any option to disable this banners in "settings". I request for an option to disable such banners.

Thanks for the nice app :)

**Comment by Livinglist** [comment]
Hi @Moxville thanks for reporting the issue! I think you are talking about the feature discovery feature. To disable that you can tap on the focused button in the overlay, I’m gonna make sure this is less confusing the upcoming version. Thanks!

**Comment by Moxville** [comment]
Thanks for the Fix. Will wait for the next release :)
