### ISSUE TITLE
"Favorite" comment action?

### ISSUE THREAD

**Issue by emacsomancer** [Livinglist/Hacki#166]
There doesn't seem to be a "favorite"/save action for comments. (Which is something that can be done in the browser and in Glider.)

**Comment by Livinglist** [comment]
Hi it’s not very straightforward, but here is how you can do it in the app right now:

https://user-images.githubusercontent.com/7277662/221375214-137542a4-1a6c-4d98-86b5-0c2fd1f395f2.MOV

**Comment by emacsomancer** [comment]
Thanks!  (Are there plans to have a "favorite" action for comments in the action menu with upvote/downvote/&c.?)

**Comment by Livinglist** [comment]
> Thanks! (Are there plans to have a "favorite" action for comments in the action menu with upvote/downvote/&c.?)

Now that you’ve mentioned, I think it makes sense to have it in the action menu, I will add it in the next release.
