### ISSUE TITLE
Add the app privacy policy to the About section 

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [Livinglist/Hacki#172]
Would be great if you had a privacy policy of the app in the About menu.

Regarding privacy policy, it is obvious that the app connects to HN servers, however it is unclear whether it sends some other data, like analytics or telemetry anywhere else. Also it is unclear whether the API requests of the logged in user somehow differ from those of one without an account (will HN know who you are if you don't post anything but use the app while logged in)

**Comment by Livinglist** [comment]
Hi, the app does collect logs but it doesn’t log any identifying information and the log file itself is stored locally on your device and won’t get sent anywhere unless you choose to do so.

The api requests are the same for both authenticated and unauthenticated users except for when you favorite/unfavorite/post/edit/upvote/downvote, in these cases, the username of logged in user will be sent out to HN to perform the corresponding action.

**Comment by Livinglist** [comment]
Noted, I will keep that in mind when working on next release.
