### ISSUE TITLE
Rename "Clear Data" to "Clear Cache"

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [Livinglist/Hacki#176]
Usually "Clear Data" means clearing all of the app data, including the settings and user account(s), so I think "Clear Cache" would be more intuitive

**Comment by yhm3ps1jfp76nkd** [comment]
Thanks for renaming but it still says "Data cleared" instead of "Cache cleared" when tapping the button

**Comment by Livinglist** [comment]
> Data cleared

missed it lol
