### ISSUE TITLE
[Question] Is it possible to add minify/shrinkResources to build.gradle?

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [Livinglist/Hacki#179]
Should probably decrease Android app size and maybe improve performance

**Comment by Livinglist** [comment]
the bulk size is mostly due to the nature of Flutter, since Flutter draws its own UI, every app made with Flutter is shipped with a Flutter rendering engine, so I doubt this is gonna make a difference but I can add it anyways.

**Comment by yhm3ps1jfp76nkd** [comment]
You were right, apk size didn't change, sorry 🤦‍♀️
