### ISSUE TITLE
System buttons bar is stuck using white button and white background on older android, whatever the theme

### ISSUE THREAD

**Issue by Porkepix** [Livinglist/Hacki#184]
On Android Oreo (8.0) stock, system buttons bar is stuck using a white background whatever the theme, and buttons are also white, therefore almost impossible to see.

See screenshot here: 
![Screenshot_20230305-231455](https://user-images.githubusercontent.com/709500/222989063-022f15d9-7686-46c6-a5fc-59128104a6ba.png)

**Comment by Porkepix** [comment]
Might be related: https://github.com/flutter/flutter/issues/119465

**Comment by Livinglist** [comment]
Hi @Porkepix do you mind sharing with me the model of phone you are using? and also what was the theme setting in the app level and system level. 

Thanks.

**Comment by Livinglist** [comment]
Gotcha thx for letting me know, I will look into it.

**Comment by Porkepix** [comment]
Well, I'm guessing this won't be possible to fix anyway, I just noticed I couldn't install versions 1.3.X marked as incompatible on F-droid, looks like the `minSdkVersion` in bump in https://github.com/Livinglist/Hacki/commit/d4778d95303314256a5e340098f025aa29852012 resulted in an Android 11+ requirement.
I'm guessing these versions are not affected by the issue given that behavior seems to have change starting with Android 9.

**Comment by Livinglist** [comment]
Seems like quite some ppl are still on android 9 (#186), I can lower the minimum sdk version and try to fix this in next release.

**Comment by Livinglist** [comment]
Upon closer examination, seems like the bottom bar has been removed in Android 9. For the sake of consistency, the minimum version requirement will be set to Android 9, really sorry for the inconvenience.

**Comment by Porkepix** [comment]
> Upon closer examination, seems like the bottom bar has been removed in Android 9. For the sake of consistency, the minimum version requirement will be set to Android 9. I’m really sorry for the inconvenience!

I don't get it, to my knowledge, there's still such a bar on following Android versions, right? As there's still these three buttons?

**Comment by Livinglist** [comment]
@Porkepix Apologies. It was misunderstanding on my part, I thought on Android 9, the three button navigation has been deprecated, while it is actually an option hidden in system settings.
