### ISSUE TITLE
Uncollapse comments

### ISSUE THREAD

**Issue by tssva** [Livinglist/Hacki#185]
When comments are collapsed clicking on "collapsed (xx)" should uncollapse the comments or the context menu should include an option to uncollapse the comments.

**Comment by Livinglist** [comment]
Hi @tssva the behavior you describe is the behavior I  implemented

**Comment by Livinglist** [comment]
Hi @tssva the first behavior you described is the one I implemented, tapping on collapsed comment will uncollapse it and its descendants. Do you mind recording a video reproducing the issue you came across?

**Comment by tssva** [comment]
I have created a [video](https://photos.app.goo.gl/JQQkqxZWyTqK3Qb3A).

After a little more playing around I have found that if tap anywhere to collapse is enabled I can collapse comments but not uncollapse them. If it is not enabled I don't seem to be able to collapse them. Maybe I'm misunderstanding where I should click on that case. The video shows the location of my screen taps.

I am using a Pixel 4 running the October 5th 2022 security update, last available for the Pixel 4, of Android 13.

**Comment by zanovis** [comment]
Having the same issue on Android 13, Pixel 6a

**Comment by Daegalus** [comment]
Can also confirm that once a comment is collapsed, you can't uncollapse it because the context menu shows up instead.

**Comment by Livinglist** [comment]
@zanovis @Daegalus Do you use screen reader?

**Comment by Daegalus** [comment]
> @zanovis @Daegalus Were you using screen reader?

No, not using anything out of the ordinary.

**Comment by Daegalus** [comment]
I recorded a quick video of hte issue: https://youtube.com/shorts/43xiWkkEuXM

My guess is when the element is collapse, the element for the Author/Time expands over the collapse element, making it impossible to click on the collapsed area to uncollapse it.
