### ISSUE TITLE
Minimum android version support 

### ISSUE THREAD

**Issue by scarlett-hill** [Livinglist/Hacki#186]
Hey,

After trying a few hacker news app, yours has become my favorite!

Is it possible to lower the minimum android  version? My smartphone is using Android 10 and I can't install your new updates now because the `minSDKVersion` is 30 while I'm 29 😭.

Cheers!

**Comment by Livinglist** [comment]
Hi @scarlett-hill, yes I can lower the minimum sdk version in next release.

**Comment by scarlett-hill** [comment]
Thank you very much! Keep up the good work!
