### ISSUE TITLE
Allow users to block stories and comments containing certain keywords

### ISSUE THREAD

**Issue by user451421541757324** [Livinglist/Hacki#188]
Hi! Would it be possible to add some kind of filter? It would be very nice to block the stories concerning ChatGPT. They are really too many, bordering on spam.

The user provides a set of keywords, and if one of them appears in a story title or comment then they are not shown.

**Comment by Livinglist** [comment]
Yes, this can be done easily.

**Comment by user451421541757324** [comment]
Thank you very much :)
