### ISSUE TITLE
Navigation to next comment of first level and same level

### ISSUE THREAD

**Issue by deadcombo** [Livinglist/Hacki#193]
Hello,

Currently we must collapse the current level comment to reach the next same level one. Furthermore, to reach the next first level comment (which often carries a diferent argument) it is necessary either scroll, often a lot, or to collapse all second level comments to reach it quicker. This makes posts with a lot of comments hard to navigate.

I suggest navigation arrows or a swipe gesture that will take you directly to the next comment of the same level as the current one and to the next root one

Thank you.

**Comment by Livinglist** [comment]
This sounds like a really useful feature. I need to figure out how to achieve this since we have pagination in place even in eager fetching mode.

**Comment by Livinglist** [comment]
added it in v1.0.5
