### ISSUE TITLE
Feature - share comment link

### ISSUE THREAD

**Issue by octoshrimpy** [Livinglist/Hacki#208]
Coming back with yet another feature!

i'd like to share the comment link, not just the comment text, as sometimes I share a comment in the middle of a thread with someone, with intention of them reading the thread, not just the out-of-context message.

**Comment by Livinglist** [comment]
hi! did you mean sharing the link to comment? if so, that is already existent, simply swipe right on a comment you want to share, tap on more, and you can find share option in the pop up menu.

**Comment by octoshrimpy** [comment]
you're right! I missed it completely.
