### ISSUE TITLE
missing a regular serif font

### ISSUE THREAD

**Issue by quite** [Livinglist/Hacki#209]
Thanks for Hacki! It's great that we can choose font for the text. But I'm missing a "regular" serif font, in addition to the (Roboto) Slab. I'm not sure which one it should be. Could the one selectable within the [Wikipedia Android app](https://github.com/wikimedia/apps-android-wikipedia) be a candidate? I don't know which one that is though.

**Comment by Livinglist** [comment]
Hi @quite, I wasn't able to find the exact name of the font family you are looking for, do u mind finding the most similar one on [Google Fonts](https://fonts.google.com/?category=Serif) and post it here.

**Comment by quite** [comment]
Hi! I suggest Noto Serif. It's the default serif font in Android, while Roboto Sans is the default sans-serif.

Nicest would perhaps be to use sans-serif for titles/headings, and the serif for all body text. But that's more work of course, and you dont have to :)

**Comment by Livinglist** [comment]
@quite Thx for the tips! I will keep them in mind for future releases.
