### ISSUE TITLE
Improve navigating by date

### ISSUE THREAD

**Issue by LazyGeniusMan** [Livinglist/Hacki#216]
Currently, navigating by date is a bit hard, when I filter by date using "from X to Y" and choose the same date (I only want to see news from that date only) it's not show anything.

![Screenshot_20230523_131609](https://github.com/Livinglist/Hacki/assets/58850480/84d39ddf-af99-4904-8b18-d6a4911cd05a)

Also when I want to go back a day, the current date chosen is not auto filled so when I already on previous month I have to renavigate to that month.

It would be nice if there is a quick way to go back/ahead a day, a week, a year, etc like this thing in website
![Screenshot_20230523_130942_Firefox](https://github.com/Livinglist/Hacki/assets/58850480/4ab70edc-aa65-4c5a-b45d-89e6c8885a39)

**Comment by jiaqi-transcarent** [comment]
Hi, thanks for suggesting these improvements! I will take a look in next release.

**Comment by Livinglist** [comment]
Hi, thanks for suggesting these improvements! I will take a look in next release.
