### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by Zuechti** [Livinglist/Hacki#22]
Hi, Thanks for making this App!

I just wanted to suggest that you publish this app on the open source app market 'f-droid'. As this application is made for tech savvy people, some of them with privacy concerns, I think this would be a good fit.

Greetings

**Comment by Livinglist** [comment]
Hi there! This app is available on F-Droid actually, I will include a link here later since it seems F-Droid website is down currently.

Thanks for reporting issues!

**Comment by Livinglist** [comment]
@Zuechti here is the link: https://f-droid.org/en/packages/com.jiaqifeng.hacki/
