### ISSUE TITLE
Custom accent color

### ISSUE THREAD

**Issue by rice7th** [Livinglist/Hacki#220]
Like the Simple Mobile Tools apps, a nice color switch that lets you change the accent color from orange to whatever color you might like would be awesome. And not only for the accent color, rather for every major color, like text, background, secondary color and so on...

**Comment by Livinglist** [comment]
Thanks for the suggestion! This can be a good addition to the app, but currently the theming is handled quite poorly in the app, making this potentially a huge refactor effort. I will see if I'm free enough to get to this in the future.

**Comment by Jontes-Tech** [comment]
Maybe have Material You dynamic colors as an option?

**Comment by rice7th** [comment]
@Jontes-Tech just like simple mobile tools then
