### ISSUE TITLE
Status/Navbar problems in night mode

### ISSUE THREAD

**Issue by wnhrt** [Livinglist/Hacki#222]
Heads up: I already encountered this in 1.5.1, after not updating for a while, and it's still there in 1.7. I couldn't downgrade with f-droid, so I don't know when exactly this bug was introduced.

When enabling night mode the navigation bar (bottom) stays white and the status bar (top) is black but apparently keeps the light mode text color (you can slightly see the battery percentage and symbol).
This happens on a Samsung device with Android 9, and you had already fixed it last year with https://github.com/Livinglist/Hacki/pull/70.

![light_mode](https://github.com/Livinglist/Hacki/assets/70302993/ff39eb70-472d-410a-8481-f3e018296b78) ![dark_mode](https://github.com/Livinglist/Hacki/assets/70302993/860763f1-b00d-4bbe-8b3f-19203ae2ffd4)

**Comment by Livinglist** [comment]
Hi @wnhrt, does the issue persist even after restarting the app?

**Comment by wnhrt** [comment]
Yes, I also tried un- and reinstalling the app

**Comment by Livinglist** [comment]
hmmm this is weird, I'm trying to reproduce this on Pixel 4 simulator with Android 9.0 but haven't succeeded, I'm wondering if this is specific to Samsung ROM.

**Comment by wnhrt** [comment]
Thank you for the quick fix!

I installed version 1.7.4 and the font color of the status bar is fixed.
But the navigation bar stays light in dark mode.
