### ISSUE TITLE
Ability to see dead comments 

### ISSUE THREAD

**Issue by RGBCube** [Livinglist/Hacki#232]
In the official HN site you can see what dead comments say, but in Hacki it doesn't show them at all, could Hacki show the comments too?

**Comment by Livinglist** [comment]
Unfortunately, it’s impossible to get text of dead comments from Hacker News official api. 

For example: https://hacker-news.firebaseio.com/v0/item/36516343.json?print=pretty

This can be walked around of course by simply extracting text from html, I will see when I can get on that later on. Thanks for suggesting improvements!

**Comment by RGBCube** [comment]
> Unfortunately, it’s impossible to get text of dead comments from Hacker News official api. 
> 
> For example: https://hacker-news.firebaseio.com/v0/item/36516343.json?print=pretty
> 
> This can be walked around of course by simply extracting text from html, I will see when I can get on that later on. Thanks for suggesting improvements!

We can ask pg to make it possible, I can send them an email. Will post updates.

**Comment by RGBCube** [comment]
I forgot this existed me. They said it was removed after clients showed deleted comments without any indication that they were deleted, and people got mad in their emails. Got ghosted after saying it could be enabled with a i_handle_deleted flag
