### ISSUE TITLE
Ability to change font size OR follow system font size

### ISSUE THREAD

**Issue by stonevil** [Livinglist/Hacki#233]
Please add ability to change font size OR follow system font size.
Default font size is too small.

Thanks.

**Comment by Livinglist** [comment]
Hi, are you on Android or iOS?

**Comment by stonevil** [comment]
> Hi, are you on Android or iOS?

Android right now. But can check on iOS. using both of them.

**Comment by Livinglist** [comment]
> 

On iOS, the app responds to system font settings, I will see what I can do for Android later on. Thanks for suggesting improvements!
