### ISSUE TITLE
Please add an option to use manual pagination instead of infinite scrolling

### ISSUE THREAD

**Issue by bishtawi** [Livinglist/Hacki#234]
I find that infinite scrolling sucks you into the app and you end up wasting more time mindless scrolling than intended.  Rather, I would like to have an option to enable pagination where you have to click a button to load the next X amount of posts. I enjoy browsing Hacker News but would like to do it in a more healthy manner.

If possible, it would be nice if the button that loads the next page indicated the page number. Something like "Load page 10" to indicate to the user that they are 10 pages deep.

**Comment by AtmanActive** [comment]
This is now implemented, kudos for that, but it's not perfect:
- the page size doesn't fit the actual android screen size, hence, again, each page needs to scroll a bit
- there is no hardware shortcut to page through
