### ISSUE TITLE
Bug parsing ) in URLs

### ISSUE THREAD

**Issue by Eiim** [Livinglist/Hacki#236]
URLs with `)` in them have the character and everything after it truncated. For example in [this port](https://news.ycombinator.com/item?id=36655314), the URL `https://www.cell.com/trends/cognitive-sciences/fulltext/S1364-6613(23)00147-X?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS136466132300147X%3Fshowall%3Dtrue` is truncated to just `https://www.cell.com/trends/cognitive-sciences/fulltext/S1364-6613(23`.

This appears to be because of the const `linkSuffix = r'(\)|]|,|\*)(.)*$'` in `constants.dart`, which is called in `rinseLink` in `link_util.dart`. Frankly, I'm not sure what the point of this is. It seems to imply that URLs shouldn't contain `)],*`, which is simply not true, all of those characters are valid in URLs.

Environment: Android, version 1.8.0 from F-Droid.

**Comment by Livinglist** [comment]
rinseLink exists because the linkify package used in the app has a url regex that often included parenthesis that shouldn't be included, I can look into this. Thx for opening the issue.

**Comment by Eiim** [comment]
Hm, perhaps rinseLink should only be used for links in comments then? I don't know how the API works but I would assume post links should work without any processing.
