### ISSUE TITLE
Keyboard obstructs text in fullscreen comment editor

### ISSUE THREAD

**Issue by deadcombo** [Livinglist/Hacki#246]
Hi.

Android 13 here. Hacki 1.8.3.

Today I wrote my first big comment.
I used the fullscreen text editor for convenience.

When the text reaches the keyboard it continues under the keyboard, making it impossible to read.
This is in contrast to the small editor which scrolls at the keyboard edge.

I tested with AOSP keyboard, 8vim and Keyboard Designer.

**Comment by Livinglist** [comment]
Thx for letting me know!

**Comment by deadcombo** [comment]
Thank you for being a great developer!
