### ISSUE TITLE
Links in comments stop at +

### ISSUE THREAD

**Issue by yonatan8070** [Livinglist/Hacki#260]
If a comment contains a link such as `https://kagi.com/search?q=multi+word+search`, only the portion of the link before the first `+` will be hyperlinked, essentially rendering some links useless.

Example:
![Screenshot_20230922-092906_Hacki](https://github.com/Livinglist/Hacki/assets/45665471/be3c0c68-262c-4c57-b570-07c258cb643e)

**Comment by Livinglist** [comment]
Thx for reporting the bug!
