### ISSUE TITLE
Ability to copy URL from the post title

### ISSUE THREAD

**Issue by Arjun9088** [Livinglist/Hacki#261]
First of all, I am extremely pleased with this app, and have been using it daily for more than a year at this point. Something I feel that could be useful, is the ability to copy URL of a post from the post's title by doing a long press on the same. There is currently no (easy) way to copy the URL of a post from within the post's title. The only option is to click the header, which opens up the default browser and copy the URL from there. Sometimes it is useful to have the ability to copy the URL ,like for  storing it somewhere else for reference, or to open it in a different browser. The home screen does have the ability to share the post, which can be then sent to something like linkhub, but this process feels too cumbersome.

If this feature is feature is already implemented and I was too dumb to find it, please ignore this issue.

**Comment by Livinglist** [comment]
Hi @Arjun9088 thanks for suggesting new features. Just in case you don’t already know, you can swipe right on the story link or text in story details page to reveal an action panel just like the one you found in home page.
