### ISSUE TITLE
Implement android 14 predictive back gesture

### ISSUE THREAD

**Issue by metronidazole** [Livinglist/Hacki#273]
It would be great if the predictive back gesture was implemented.

As a test I added the  android:enableOnBackInvokedCallback="true" attribute to AndroidManifest and that enabled it succesfully, however it had unexpected behaviour in that using the back button within a post will exit to the launcher as opposed to the main page.

https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture

**Comment by Livinglist** [comment]
Seems like it is not yet properly supported in Flutter 3.13, it is in Flutter 3.14, I will get on it after 3.14 is released.
