### ISSUE TITLE
Feature request : Add search sorting 

### ISSUE THREAD

**Issue by fedikhatib** [Livinglist/Hacki#299]
Hi great work and nice app.
Can you add a search sorting option to sort by :
- Best (most upvotes)
- Newest
- Oldest 
And maybe enhance the horizonal option list ( maybe hiding when scrolling down)

**Comment by Livinglist** [comment]
There is already a chip button that enables you to sort results so that newest result comes first and unfortunately, according to https://hn.algolia.com/api, there doesn’t seem to be a way to sort results by points or by date so that oldest comes first. Please lemme know if I’m missing anything.
