### ISSUE TITLE
Explicit support for exact match search

### ISSUE THREAD

**Issue by meenbeese** [Livinglist/Hacki#301]
Currently, the search tool only does related searches by default, which can be confusing when trying to find a specific term. For example, searching for ```java``` returns results for ```javascript``` as well.

The only possible way to to do exact search is by putting the search query is quotes, which is not easily findable and not mentioned. Please add a checkbox or button to conveniently toggle this behavior when searching for a term.

**Comment by Livinglist** [comment]
Hi, thanks for suggesting improvements for Hacki. Under the hood, we are just using the Hacker News search API provided by Algoli of which the documentation you can find here: https://hn.algolia.com/api. This method of exact match isn’t at all mentioned inside its documentation, I’m just curious about how or where you found out about it.

**Comment by meenbeese** [comment]
Hello, I did not know of the API documentation and discovered this while tinkering with the app myself. It seems strange that they never officially mentioned this.

I also see the linked PR and thank you for being so fast in resolving the issue. I really enjoy using Hacki, it is a great app.

**Comment by Livinglist** [comment]
> Hello, I did not know of the API documentation and discovered this while tinkering with the app myself. It seems strange that they never officially mentioned this.
> 
> I also see the linked PR and thank you for being so fast in resolving the issue. I really enjoy using Hacki, it is a great app.

Thanks for your kind words and it is my pleasure building an app you enjoy using.
