### ISSUE TITLE
[feat] a quick way to mark as read

### ISSUE THREAD

**Issue by huyz** [Livinglist/Hacki#311]
Perhaps swiping left on a story?
Tapping in and going out is too slow, especially if we just want to mark as read because we're just not interested in that story

**Comment by Livinglist** [comment]
Hi, have you tried this setting? 
![IMG_5527](https://github.com/Livinglist/Hacki/assets/7277662/e826b242-70fc-4169-8eef-243f0f098e11)

**Comment by huyz** [comment]
Yes I have, but it's not my cup of tea.  I prefer taking actions to signify that I've read something.  I've done the same with Gmail, Feedly, Usenet, etc.

**Comment by Livinglist** [comment]
@huyz can you show me some screenshots or recordings of the UX you are looking for? I tried to find such settings in Gmail app but didn't find anything.

**Comment by huyz** [comment]
I made a few screen captures. Will post soon. Just busy right now

**Comment by huyz** [comment]
Here is how to change the settings in Gmail:

https://github.com/Livinglist/Hacki/assets/128394/1d5e747e-2934-4ec5-abaa-11b381b02634

And here is how swiping looks in Gmail:

https://github.com/Livinglist/Hacki/assets/128394/3b671035-718e-48a7-b840-b7a6c1f7441c

Here is how to change the settings in Apple Mail:

https://github.com/Livinglist/Hacki/assets/128394/d5de50cc-e8bc-4b51-b6ff-454e539beba0

And here is how swiping looks in Apple Mail:

https://github.com/Livinglist/Hacki/assets/128394/098cf19f-c6d2-4977-8376-ca386ab65172


Note that above Apple Mail is more flexible than Gmail as it supports two swipe actions:

1. Swipe gently and then press the button you want
2. Swipe completely for a shortcut to the main button

If you didn't catch the difference, here's another clip:

https://github.com/Livinglist/Hacki/assets/128394/b80c3a9f-05c4-4e0b-8565-1b8bb3f6d892



Btw, ideally what I would like to have is  an Archive action in addition to a Read action.  If I had an Archive action, then my feature request would actually not be for a "quick way to mark as read"—it would be for a "quick way to archive".
But I understand that you may not want to complicate the UI and add even more states (and unlike with email, it's not that critical that a newsreader distinguish between reading and archiving).


Thanks for considering. Great job on all UI btw.  You've implemented a lot of complex features but managed to keep the UI simple.

**Comment by Livinglist** [comment]
@huyz thx for these, really helpful.

**Comment by huyz** [comment]
Tried it. Beautiful work. Thank you!
