### ISSUE TITLE
Can't find the black mode since the update 

### ISSUE THREAD

**Issue by RocketRene** [Livinglist/Hacki#351]
I am using version 2.5.0 on Android and since the ui update ,there is no more setting for the black background. 
Is this planned  in the future ?

**Comment by Livinglist** [comment]
Hi @RocketRene! I removed True Dark mode in v2.4.0 since the color scheme wasn't playing along with the black background but the issue has been fixed in the latest release of Flutter, and True Dark mode is coming back in v2.6.0, thank you.
