### ISSUE TITLE
Feature request: Please add 'best' stories and other lists

### ISSUE THREAD

**Issue by Efreak** [Livinglist/Hacki#36]
Currently there's tabs at the top for *top*, *new*, *show*, *ask*, and *jobs*. Please add a new tab for the *best* list. It might be worthwhile to consider adding *pool*, *active*, *invited* as well (see [lists](https://news.ycombinator.com/lists) for all lists available).

**Comment by Livinglist** [comment]
I'm still hesitating whether or not to add more tabs to the tab bar since I want to keep the app as minimalistic as possible. Perhaps I could add a tab bar customization feature where users can choose what they want in the tab bar. As for stories from lists like pool/active/invited etc, I don't think they are included in the official HN api, so need to figure out how to get theirs ids. Worst case is I need to scrap them from the website directly.

**Comment by Efreak** [comment]
It appears that while best stories are in the API, you are correct that pool/active/invited are not; I simply assumed they were. If you're not already scraping anything, then I wouldn't bother adding those.

I haven't used hacki on a phone screen yet, so unsure how it appears there, however if you do add more tabs at the top, this might be combined with the fullscreen request, as displaying the article list in fullscreen rather than a sidebar would provide extra room for tabs at the top. Alternatively, you could 1. Make the discussion items displayed in the main screen and profile tab configurable (would allow users to make search, inbox, submit more prominent) 2. Make the tab bar scroll horizontally or 3. Combine the top controls of both columns/panes into a single action bar with tabs at left, continuing as far as necessary until pin/save/open at right.

Personally, I'm in favor of extreme density of information over looks, so keep in mind that my suggestions won't necessarily be good for the app. Despite thinking it would look bad myself, I would happily collapse comments to a half-height line (rather than two lines), and would probably also collapse multiple same-level comments into one as well, like GitHub comments does on long discussions.

**Comment by Livinglist** [comment]
Replaced jobs with best stories in #41
