### ISSUE TITLE
Feature request: a way to expand the content view to fullscreen on tablets

### ISSUE THREAD

**Issue by Efreak** [Livinglist/Hacki#38]
I'm using a 10" tablet, and when I open a story, I'd prefer to see only the comments on that story, and not also see the list of articles. It would be nice to have either of the following:

1. A setting to emulate the (I assume) mobile view down in the screenshots, where only comments and not stories are shown
2. A button to expand the current view to fullscreen

**Comment by Efreak** [comment]
I've noticed that if I open a link from another app, the comments show up in a fullscreen view instead of showing the list of articles. Perhaps tapping on the story a second time could open the same fullscreen comments view?

**Comment by Livinglist** [comment]
@Efreak this is what I came up with:

https://user-images.githubusercontent.com/7277662/172039651-0654bf8d-c7e4-4873-b6b8-9dc84511990a.mov
