### ISSUE TITLE
Feature Request: Add option to open post directly rather than jumping straight to comments

### ISSUE THREAD

**Issue by JacobBumgarner** [Livinglist/Hacki#388]
The title explains it all.

Loving this app so far!

**Comment by Livinglist** [comment]
hi you can directly open up the url by tapping on the image.

**Comment by JacobBumgarner** [comment]
I currently have the images turned off (complex story title off). Is there somewhere to click on those cards to open the link?

**Comment by Livinglist** [comment]
Hi @JacobBumgarner , starting with v2.8, you can now long press on story tile to go directly to the web page.

**Comment by JacobBumgarner** [comment]
Thanks!
