### ISSUE TITLE
Feature request: View other user profiles from comments

### ISSUE THREAD

**Issue by Efreak** [Livinglist/Hacki#45]
The API makes [user info](https://github.com/HackerNews/API#users) available, such as user's total points (slightly interesting), profile information (important, sometimes has contact info) and the date the profile was created (can be useful to know if it was made the same day sometimes). Please implement at least the profile data in Hacki. Suggested method is tapping on the username on a comment, but the comment menu may work better.

**Comment by Livinglist** [comment]
you got it. coming in v0.2.17
