### ISSUE TITLE
Tablet mode optimization

### ISSUE THREAD

**Issue by mrusme** [Livinglist/Hacki#466]
First of all, thank you for the work on this solid client! I enjoy using it and have been trying it lately on a Pixel Tablet device. Unfortunately the submissions list is unconfortably small on such a device:

![Screenshot_20240830-212941](https://github.com/user-attachments/assets/4d4af36d-9453-4a41-9ac5-f985bc4c73c2)
![Screenshot_20240830-213000](https://github.com/user-attachments/assets/6e2bc22c-6d56-48ce-8367-ceb6c923059e)

Would it be possible to increase the width of the list without much effort? Or maybe make it full width in portrait mode?

Thank you kindly for your effort.

**Comment by mitanshu7** [comment]
Hello,

Thanks for the awesome work!

I found a small "bug". When you added the option to resize links and comments in tablet mode, please add some thresholds. 

For example, when using gesture navigation in android, it becomes impossible to resize if you take the bar to extremes. See pic.

![Screenshot_2024-10-24-19-36-29-61_a4cc5d72270e66b9bb8cebf0fde3bfdf.jpg](https://github.com/user-attachments/assets/669e1ec4-258f-4f88-a9cc-4fa444a2376b)

Current workaround involves ressetinh the app or changing navigation in android settings.
