### ISSUE TITLE
White borders on app icon

### ISSUE THREAD

**Issue by rask0lnikow** [Livinglist/Hacki#75]
When using the Pixel launcher, the app-icon is displayed with small white spots at the bottom and on the right side of the orange background.

Using the Nova Launcher, however, the icon is displayed correctly.

It's a small thing, but now that I've seen it once, I can't unsee it.

![Screenshot_20221119-202232_Pixel Launcher](https://user-images.githubusercontent.com/118631199/202868094-e88910a2-2b92-4b6e-8a50-de19b0f8adb5.png)

**Comment by Livinglist** [comment]
Hi, thanks for opening the issue. Did you install the app using Google Play or F-droid?

**Comment by rask0lnikow** [comment]
I installed it using F-droid

**Comment by Livinglist** [comment]
Hi there, the fix for the icon issue is gonna be in release v0.2.33. Thanks for reporting the issue!
