### ISSUE TITLE
Split abi

### ISSUE THREAD

**Issue by linsui** [Livinglist/Hacki#77]
The apk is too large for a news reader... Could you please add something like https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L94 so that we can build smaller apks with single abi? Thanks!

**Comment by Livinglist** [comment]
Sure thing! Should I re-create the tag after the change is merged?

**Comment by linsui** [comment]
Thanks! Could you please add flutter as a submodule so that we don't need to bump the flutter version manully? 

> Should I re-create the tag after the change is merged?

It's not needed, we can point to the commit.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12286

**Comment by Livinglist** [comment]
I have just added Flutter as a submodule, anything else I should do?

**Comment by linsui** [comment]
I'll update the build metadata for the next version to use the flutter from the submodule. Thanks!
