### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [Livinglist/Hacki#8]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by Livinglist** [comment]
Hi there. I’m currently working on including Hacki in F Droid, here is the [issue](https://gitlab.com/fdroid/rfp/-/issues/2020), since F Droid doesn’t allow google play core as dependency, I’m planning to remove in app review package from the app. It will be done within next two weeks hopefully.
